// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1647924413);
user_pref("app.update.lastUpdateTime.region-update-timer", 1647492569);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1647924173);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1647924293);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1647492119);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1647924533);
user_pref("browser.region.update.updated", 1647492570);
user_pref("browser.search.region", "IN");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1647409846648");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1647924415);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220106182030");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"f3ff4c36-33b3-4c93-a1fb-c4bf99599b59\",\"google@search.mozilla.org\":\"738d967b-f128-42bf-a2bb-bb3585d6bff6\",\"ddg@search.mozilla.org\":\"1fad2038-f6e1-428f-9021-487fd93faf33\",\"amazondotcom@search.mozilla.org\":\"5da0de7e-9688-4c23-98fc-be9da4287988\",\"wikipedia@search.mozilla.org\":\"70c5f12f-5fcd-4bac-bbb8-85b119204279\",\"bing@search.mozilla.org\":\"44d3850a-e2d5-4deb-9248-a3bf53af0e84\"}");
user_pref("idle.lastDailyNotification", 1647926469);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "1b088c9b-bc52-46c4-aa11-f1dc74af769");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.5.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1647926469);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -8652);
user_pref("services.settings.last_etag", "\"1647418983146\"");
user_pref("services.settings.last_update_seconds", 1647932945);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1647932945);
user_pref("services.settings.thunderbird.search-config.last_check", 1647932945);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1647932945);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1647926469);
user_pref("toolkit.telemetry.cachedClientID", "48ce9a4f-decb-48a6-9c4b-31da81fc9281");
user_pref("toolkit.telemetry.previousBuildID", "20220106182030");
